apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/xxavarlonxx/kubeops.git
    targetRevision: development
    path: jenkins
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
